version: "3"
services:
  db:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_DATABASE: hello_spring
      MYSQL_USER: hello-spring
      MYSQL_PASSWORD: hello-spring
      MYSQL_ROOT_PASSWORD: hello-spring
    volumes:
      - ./db/.data:/var/lib/mysql/:rw
    ports:
      - "3306:3306"
    restart: always

  app:
    image: tprogramer/hello-spring:0.0.1
    container_name: application
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/hello_spring?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "hello-spring"
      SPRING_DATASOURCE_PASSWORD: "hello-spring"
